from typing import List, Tuple

cars_db: List[Tuple[str, int, int, List[str]]] = [
    ("China", 1, 2023, ["Wuling Hongguang Mini EV", "Tesla Model Y", "BYD Qin Plus"]),
    ("India", 2, 2023, ["Maruti Suzuki Alto", "Maruti Suzuki Swift", "Hyundai Creta"]),
    ("United States", 3, 2023, ["Ford F-Series", "Chevrolet Silverado", "Ram Pickup"]),
    ("Indonesia", 4, 2023, ["Toyota Avanza", "Honda Brio", "Mitsubishi Xpander"]),
    ("Pakistan", 5, 2023, ["Suzuki Mehran", "Toyota Corolla", "Honda Civic"]),
    ("Brazil", 6, 2023, ["Chevrolet Onix", "Hyundai HB20", "Fiat Strada"]),
    ("Nigeria", 7, 2023, ["Toyota Corolla", "Toyota Hilux", "Honda Accord"]),
    ("Bangladesh", 8, 2023, ["Toyota Hilux", "Toyota Corolla", "Honda City"]),
    ("Russia", 9, 2023, ["Lada Granta", "Kia Rio", "Hyundai Solaris"]),
    ("Mexico", 10, 2023, ["Nissan Versa", "Chevrolet Silverado", "Toyota Hilux"]),
    ("Japan", 11, 2023, ["Toyota Corolla", "Honda Fit", "Nissan Note"]),
    ("Ethiopia", 12, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Philippines", 13, 2023, ["Toyota Vios", "Mitsubishi Mirage", "Honda City"]),
    ("Egypt", 14, 2023, ["Chevrolet Aveo", "Hyundai Elantra", "Toyota Corolla"]),
    ("Vietnam", 15, 2023, ["Toyota Vios", "Honda City", "Mitsubishi Xpander"]),
    ("DR Congo", 16, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Turkey", 17, 2023, ["Renault Clio", "Fiat Egea", "Volkswagen Golf"]),
    ("Iran", 18, 2023, ["Peugeot 405", "Pride", "Samand"]),
    ("Germany", 19, 2023, ["Volkswagen Golf", "Volkswagen Tiguan", "BMW 3 Series"]),
    ("Thailand", 20, 2023, ["Toyota Hilux", "Isuzu D-Max", "Honda City"]),
    ("United Kingdom", 21, 2023, ["Vauxhall Corsa", "Ford Fiesta", "Volkswagen Golf"]),
    ("France", 22, 2023, ["Peugeot 208", "Renault Clio", "Dacia Sandero"]),
    ("Italy", 23, 2023, ["Fiat Panda", "Fiat 500", "Lancia Ypsilon"]),
    ("South Africa", 24, 2023, ["Toyota Hilux", "Ford Ranger", "Volkswagen Polo"]),
    ("Tanzania", 25, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Myanmar", 26, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("South Korea", 27, 2023, ["Hyundai Sonata", "Kia Sorento", "Genesis G80"]),
    ("Colombia", 28, 2023, ["Chevrolet Spark", "Renault Sandero", "Mazda CX-5"]),
    ("Kenya", 29, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Spain", 30, 2023, ["Dacia Sandero", "Renault Clio", "Volkswagen Golf"]),
    ("Uganda", 31, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Sudan", 32, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Ukraine", 33, 2023, ["Toyota Land Cruiser", "Hyundai Tucson", "Kia Sportage"]),
    ("Iraq", 34, 2023, ["Toyota Land Cruiser", "Mitsubishi Pajero", "Hyundai Tucson"]),
    ("Afghanistan", 35, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Poland", 36, 2023, ["Skoda Octavia", "Volkswagen Golf", "Toyota Corolla"]),
    ("Canada", 37, 2023, ["Ram 1500", "Ford F-Series", "Chevrolet Silverado"]),
    ("Morocco", 38, 2023, ["Renault Clio", "Peugeot 208", "Dacia Sandero"]),
    ("Saudi Arabia", 39, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Hyundai Tucson"]),
    ("Uzbekistan", 40, 2023, ["Chevrolet Spark", "UzAuto Nexia", "Toyota Corolla"]),
    ("Malaysia", 41, 2023, ["Perodua Myvi", "Proton Saga", "Honda City"]),
    ("Afghanistan", 42, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Angola", 43, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Mozambique", 44, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Ghana", 45, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Yemen", 46, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Nepal", 47, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Venezuela", 48, 2023, ["Chevrolet Aveo", "Hyundai Elantra", "Toyota Corolla"]),
    ("Madagascar", 49, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Cameroon", 50, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("Côte d'Ivoire", 51, 2023, ["Toyota Hilux", "Toyota Land Cruiser", "Mitsubishi Pajero"]),
    ("North Korea", 52, 2023, ["Pyeonghwa Motors Hwiparam", "Samjiyon", "Bengung-401"]),
]

